### ISSUE TITLE
Support for one-network-card card configuration, single card configuration, one NIC only

### ISSUE THREAD

**Issue by interduo** [LibreQoE/LibreQoS#48]
> Is it possible to use LibreQoS on one network card using different VLANs or just use one interface for network conectivity?

> I don't think https://github.com/xdp-project/xdp-cpumap-tc/issues/7. xdp-cpumap-tc is what we use to redirect packets to the appropriate CPU quickly. If you follow [this network design](https://raw.githubusercontent.com/rchac/LibreQoS/main/docs/design.png), you can have any VLANs desired on the Core router at least, and as they pass, routed, over the LibreQoS box, they'll be shaped correctly.

Now I have 1x40G QSFP+ card - here on the test machine - I thought that I could use vlan interface
```
ens1np0.100 
ens1np0.101
```
for networking.

The target for production is to:
- connect LibreQoS VM router to two different core switches,
- with two passthrough network interfaces and set some teaming (bridge,bond,lacp...)
- make the same on backup router with but with bigger path costs,

So I need six 1x40G cards or three 2x40G cards. (2x interfaces for BGP VM, 4x interfaces for LibreQoS)
Is that a problem? It depends.

This would results in:
- providing better ressistance from unpredictable events.
(switch/QSFP cable/QSFP module serwer/QSFP switch module/more things failure),
- better maintance (and don't fear about upgrades),

I am just asking because I would like to make sure of design.png.

If we use OSPF (L3) and src/dst address (L3) - Can we use only one network card when the sumarized network throughoutput is less than 40% of total maximum sumarized (upload+download) throughoutput?

Is this sentence from README.txt:
"NIC must have two or more interfaces for traffic shaping." is a requirement or just recomendation?

On LibreQoS there is no NAT - so this is possible I think. Am I right?

Maybe we could use https://man7.org/linux/man-pages/man8/tc-vlan.8.html ?

**Comment by interduo** [comment]
Probbably this is some kind of duplicate of https://github.com/rchac/LibreQoS/issues/41.

**Comment by interduo** [comment]
I would like to get something like that:
https://raw.githubusercontent.com/interduo/LibreQoS/354141a766e19c313301b3f0824cc010330cc650/diagram-test.drawio

![image](https://user-images.githubusercontent.com/17087236/187510287-6e77a7a3-8890-4b8b-a0f3-dd71d3b8fc9b.png)

**Comment by interduo** [comment]
@rchac how big is performance dropdown when using virtio instead of passthrough NICs? Did You try to use SRIOV instead of PCI-Passthrough?

**Comment by rchac** [comment]
> @rchac how big is performance dropdown when using virtio instead of passthrough NICs? Did You try to use SRIOV instead of PCI-Passthrough?

Virtio / generic XDP is about 1/4 the performance of pass-through NIC. Iam testing out a bare metal server and it's working great so far.

**Comment by interduo** [comment]
Did You tested SRIOV?

**Comment by rchac** [comment]
> Did You tested SRIOV?

I don't think SRIOV works with XDP. But it *may* be possible.

**Comment by interduo** [comment]
If yes then we could make a LibreQoS ospfd neighbour and add two /32 networks between EDGE router and CORE switch. SRIOV overhead is about 2 or less %

**Comment by dtaht** [comment]
We haven't been in a position to document or discuss virtualization all that much, and it makes my head hurt. We did just aquire some serious resources from equinix #151 to be able to test this more fully, but I kind of consider virtualization testing to be a whole other "project", after we get a solid test suite in #153. @interduo Interduo, though, since you have the resources, goferit with v1.3 and get back to us? 

Secondly, I like the idea1 card operation a LOT, but don't know if that works in 1.3?

**Comment by interduo** [comment]
Now I use 1.2 version as VM. It's doing it works.

I will get You a feedback but my local roadmap needs few hw changes so it will take us few weeks. And I will test firstly one interface configuration.

**Comment by rchac** [comment]
What happens when you run
```
tc class show dev v800
tc class show dev v900
```

**Comment by thebracket** [comment]
I did a little digging (ran into some hyper-v issues with tagged VLANs between VMs; I need to get a better test environment locally!). So there's good news and bad news:

The *good* news is that binding XDP programs to VLAN interfaces works. I can bind an XDP program to a VLAN I've created (in this case `eth1.8`), and it functions.

The *bad* news is that performance is going to be really, really bad:

* There's only 1 queue on a VLAN interface. `ls /sys/class/net/eth1.8/queues/` shows `rx-0` and `tx-0`. So CPU mapping won't do anything, because there's only one queue to map - it's going to sit on a single core, no matter what you do.
* VLAN interfaces appear as "XDP generic" (which means "SKB bind mode" internally); if your interface had any hardware acceleration for XDP, it just went away.

So my advice: don't do this.

**Comment by thebracket** [comment]
Is there a way to unlink this from issue 26? They aren't really related. 26 is talking about VLANs inside the bridge - which works really well, I'm pushing 2gbit/s through VLANs in a shaping bridge right now. This is talking about the top-level bridge members being VLANs. (We should probably close 26)

**Comment by interduo** [comment]
Vlan interface use NIC queues

**Comment by thebracket** [comment]
Looking at the config, I see a couple of things:

```
interfaceA = 'v800@ens16np0'
interfaceB = 'v900@ens16np0'
```

Isn't going to work, because the devices are named `v800` and `v900`. You should see entries in `/sys/class/net/v800/queues` and `/sys/class/v900/queues`.

Since there's almost certainly only 1 queue (per direction), you're going to want to look in `/sys/class/net/ens12np0/queues` and see how many there actually are. Add `queuesAvailableOverride=(the number of queues)` to your config to bypass the test.

**Comment by interduo** [comment]
Sorry for not editing my earlier full post.

I did it now - interfaces are named corectly in `ispConfig.py` and in netplan YAML. I did use `queuesAvailableOverride=16`.

Maybe it's another idea/technology to use one card without vlans?

**Comment by interduo** [comment]
So having two core switches and no SPOF comes with requirement now:
LibreQoS - 2
Second LibreQoS - 2
BGP - 1
Second BGP - 1
Internet Upsteams - >=2
another core switch - 2 (one switch-switch link)

So we need minimum 10x QSFP+ ports WRR 

That is not a thing for 10G network through but the stairs shows when we are above that line.
Just look at the market and see that all switches in **resonable** prices comes with only 4xQSFP+.

**Comment by interduo** [comment]
I saw https://github.com/LibreQoE/LibreQoS/commit/be2e2fbd1ec45bf65e9677e2a0452e59161ebc0c
@thebracket do You know how big is performance penalty (and if is any) using only one interface instead of two?

**Comment by thebracket** [comment]
Based on testing on the Equinix servers, the performance hit is pretty
tiny. We've pushed 25 gbps through a single-card ("on a stick") setup on a
16 core (32 virtual cores, but we turned off hyperthreading) with CPU to
spare. I honestly don't know what the upper limit is, since we're
saturating our 25 gbps test and don't have anything bigger to test with!
